[book]
authors = ["fabito"]
language = "pt-br"
multilingual = false
src = "src"
title = "Sourdough Recipes"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/fkramos/sourdough-recipes"
mathjax-support = true